server:
  port: 8080
spring:
  application:
    name: server-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
zuul:
  host:
      connect-timeout-millis: 10000
      socket-timeout-millis: 60000
  routes:
    shop:
      path: /product/**
      serviceId: module-shop
      stripPrefix: false
    app:
      path: /app/**
      serviceId: module-app
      stripPrefix: false