server:
    port: 80
spring:
  application:
    name: server-zuul
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
zuul:
  routes:
    shop:
      path: /product/**
      serviceId: module-shop
      stripPrefix: false
    app:
      path: /app/**
      serviceId: module-base
      stripPrefix: false
    file:
      path: /file/**
      serviceId: module-file
      stripPrefix: false
    upload:
      path: /upload/**
      serviceId: module-file
      stripPrefix: false
    code:
      path: /code/**
      serviceId: module-code
      stripPrefix: false
    advertisement:
      path: /advertisement/**
      serviceId: module-cms
      stripPrefix: false
    toolbar:
      path: /toolbar/**
      serviceId: module-cms
      stripPrefix: false
    article:
      path: /article/**
      serviceId: module-cms
      stripPrefix: false
    navigation:
      path: /navigation/**
      serviceId: module-cms
      stripPrefix: false
    role:
      path: /role/**
      serviceId: module-base
      stripPrefix: false
    user:
      path: /user/**
      serviceId: module-base
      stripPrefix: false
    menu:
      path: /menu/**
      serviceId: module-base
      stripPrefix: false
    admin:
      path: /admin/**
      serviceId: module-base
      stripPrefix: false
    forum:
      path: /forum/**
      serviceId: module-sns
      stripPrefix: false
    topic:
      path: /topic/**
      serviceId: module-sns
      stripPrefix: false
    wawi:
      path: /wawi/**
      serviceId: module-wawi
      stripPrefix: false
    member:
      path: /member/**
      serviceId: module-member
      stripPrefix: false
  okhttp:
    enabled: true # 使用okhttp方式请求，正常来说okhttp比较速度快一点
  semaphore:
    max-semaphores: 500 # 并发处理数，值越大越好，但到到达一个临界点之后，就不会提高响应速度了
  host:
    socket-timeout-millis: 30000 # socket超时时间，如果使用service-id方式是不用配置的
    connect-timeout-millis: 30000 # 连接时间semaphores
    max-total-connections: 5000  # 最大连接数，值越大越好，但到到达一个临界点之后，就不会提高响应速度了
    max-per-route-connections: 5 # 每个router最大连接数，降低请求时间，越小越好，但达到一定层级就没用了

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000 # Hystrix超时时间
          strategy: THREAD

ribbon:
  ReadTimeout: 10000 # 处理时间
  ConnectTimeout: 10000 # 连接时间
  MaxAutoRetries: 0 #最大自动重试次数
  OkToRetryOnAllOperations: true #对所有操作请求都进行重试
  MaxAutoRetries: 10 #对当前实例的重试次数
  MaxAutoRetriesNextServer: 10 # 换实例重试次数
  MaxTotalHttpConnections: 2000 # 最大http连接数，越大越好，但到到达一个临界点之后，就不会提高响应速度了
  MaxConnectionsPerHost: 1000 # 每个host连接数