server:
  port: 8080
spring:
  application:
    name: server-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
zuul:
  host:
      connect-timeout-millis: 10000
      socket-timeout-millis: 60000
  routes:
    shop:
      path: /product/**
      serviceId: module-shop
      stripPrefix: false
    app:
      path: /app/**
      serviceId: module-base
      stripPrefix: false
    code:
      path: /code/**
      serviceId: module-base
      stripPrefix: false
    advertisement:
      path: /advertisement/**
      serviceId: module-cms
      stripPrefix: false
    article:
      path: /article/**
      serviceId: module-cms
      stripPrefix: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
     ConnectTimeout: 3000
     ReadTimeout: 60000