server:
  port: 8080
spring:
  application:
    name: server-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
zuul:
  routes:
    shop:
      path: /product/**
      serviceId: module-shop
      stripPrefix: false