server:
  port: 8070

logging:
  level:
    root: info

eureka:
  instance:
    hostname: 192.168.31.172
    leaseRenewalIntervalInSeconds: 5
  server:
    # 开发环境设为false，关闭自我保护机制，服务器不推荐使用
    enable-self-preservation: false
    # 清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 4000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
